### PR TITLE
Single mass sink in layer 2

### PR DESCRIPTION
**Pull request by fdf2002**
@hdrake Here is a single mass sink; adding a second one shouldn't be too hard now!

### CODE REVIEW

**Comment by fdf2002** [comment]
This seems to be mostly working, but I'm noticing that every few time steps, all the layers seem to lose a small amount of thickness, even when KD=0.0 (no vertical diffusion) and REGRIDDING_TIME_SCALE is large enough to never remap. Currently looking into the issue (and whether it even is an issue at all), but any feedback is appreciated!

**Comment by fdf2002** [comment]
Upon further investigation, I've found that in total, the level is decreasing by the correct amount of (velocity * dt). I guess there is some minor readjustment of the vertical grid going on, even when the main regridding process is not happening. I'll push my updated test notebook to demonstrate these results.

**Comment by hdrake** [comment]
> Upon further investigation, I've found that in total, the level is decreasing by the correct amount of (velocity * dt). I guess there is some minor readjustment of the vertical grid going on, even when the main regridding process is not happening. I'll push my updated test notebook to demonstrate these results.

Hmm, I'm not sure what's happening either. I would say let's not worry about it for now. I saw you implemented a second mass sink in the MOM6 code. I'll be excited to see the results of the layers with that on!

**Comment by hdrake** [comment]
@fdf2002, this looks like some really nice progress! Let me know if there are particularly parts of the code you'd like me to look at this week.

I've just read through the code changes and it looks good to me at first glance, but I have not tried running it or scrutinizing every line in detail. It looks like the next step, which you've currently got as a placeholder comment, is to add the tracers back in?
https://github.com/hdrake/MOM6/blob/7faac627b65cd79ddc8294a398720fb137b8b155/src/parameterizations/vertical/MOM_otec.F90#L193-L195

Is that right?

I also like how you've created this horizontal `otec_step` wrapper for the all of the mass sinks/sources which operate on individual columns. Nice!

https://github.com/hdrake/MOM6/blob/7faac627b65cd79ddc8294a398720fb137b8b155/src/parameterizations/vertical/MOM_otec.F90#L201-L279

Is there anything else that needs to be done for the core `otec` subroutines besides updating the tracer concentrations in the `source` layer? It will be interesting to see how this plays out in the 1D model under a few different parameter regimes!

**Pull request merged**
